/* eslint-disable no-unused-vars */
export enum UserType {
  USER = 'USER',
  BOTH = 'BOTH',
  ADVERTISER = 'ADVERTISER',
}

export enum TASKTYPE {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CLAIMED = 'CLAIMED',
  EXPIRED = 'EXPIRED',
  COMPLETEDANDEXPIRED = 'COMPLETEDANDEXPIRED',
  CLAIMEDANDEXPIRED = 'CLAIMEDANDEXPIRED',
}
